---

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - docker_sd_version == "latest"
  block:
    - name: get latest release
      bodsch.scm.github_latest:
        project: bodsch
        repository: docker-sd
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: set docker-sd version
      ansible.builtin.set_fact:
        docker_sd_version: "{{ _latest_release.latest_release }}"

- name: define download information
  ansible.builtin.set_fact:
    docker_sd_release: "{{ docker_sd_defaults_release | combine(docker_sd_release, recursive=True) }}"

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    docker_sd_delegate_to: "{{ ansible_host }}"
    docker_sd_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/docker-sd', true) }}/{{ docker_sd_version }}"
  when:
    - docker_sd_direct_download

- name: create download directory
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ docker_sd_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: detect the downloaded docker_sd archive
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ docker_sd_local_tmp_directory }}/{{ docker_sd_release.file }}"
  register: stat_docker_sd_archive

- name: download
  when:
    - stat_docker_sd_archive.stat is defined
    - not stat_docker_sd_archive.stat.exists | default('false')
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: bodsch
            repository: docker-sd
            checksum_file: "{{ docker_sd_release.checksum }}"
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "{{ docker_sd_version }}"
          register: _latest_checksum

        - name: define checksum for {{ system_architecture }} architecture
          ansible.builtin.set_fact:
            __docker_sd_checksum: "sha256:{{ _latest_checksum.checksum }}"
          when:
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download docker_sd binary archive
      become: false
      delegate_to: "{{ docker_sd_delegate_to }}"
      run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ docker_sd_release.download_url }}/download/{{ docker_sd_version }}/{{ docker_sd_release.file }}"
        dest: "{{ docker_sd_local_tmp_directory }}/{{ docker_sd_release.file }}"
        checksum: "{{ __docker_sd_checksum | default(omit) }}"
        mode: 0660
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ docker_sd_delegate_to }}"
      run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ docker_sd_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect extracted binary
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ docker_sd_local_tmp_directory }}/{{ docker_sd_release.binary }}"
  register: stat_docker_sd_binary

- name: extract docker_sd archive
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ docker_sd_local_tmp_directory }}/{{ docker_sd_release.file }}"
    dest: "{{ docker_sd_local_tmp_directory }}/"
    copy: false
    #extra_opts:
    #  - --strip-components=1
  when:
    - stat_docker_sd_binary.stat is defined
    - not stat_docker_sd_binary.stat.exists | default('false')

...
