---

nginx_exporter_version: '0.9.0'
nginx_exporter_nginx_plus: false

nginx_exporter_system_group: nginx-exporter
nginx_exporter_system_user: "{{ nginx_exporter_system_group }}"
nginx_exporter_config_dir: /etc/nginx_exporter

nginx_exporter_direct_download: false

nginx_exporter_release:
  download_url: https://github.com/nginxinc/nginx-prometheus-exporter/releases
  file: nginx-prometheus-exporter_{{ nginx_exporter_version }}_{{ ansible_system | lower }}_{{ system_architecture }}.tar.gz

nginx_exporter_service: {}
#   nginx:
#     plus: false
#     retries: 3
#     retry_interval: 10s
#     scrape_uri: http://127.0.0.1:8080/stub_status
#     ssl_ca_cert: ""
#     ssl_client_cert: ""
#     ssl_client_key: ""
#     ssl_verify: ""
#     timeout: "10s"
#   prometheus:
#     const_labels: {}
#   web:
#     listen_address: "127.0.0.1:9113"
#     secured_metrics: ""
#     ssl_server_cert: ""
#     ssl_server_key: ""
#     telemetry_path: /metrics

nginx_exporter_bin: /bin/nginx_exporter

...
