---

docker_sd_version: "0.10.0"

docker_sd_system_user: docker-sd
docker_sd_system_group: docker-sd
docker_sd_config_dir: /etc/docker-sd

docker_sd_direct_download: false

docker_sd_release: {}
docker_sd_rest_api: {}
docker_sd_hosts: []
docker_sd_addition_labels: []

...
