---

galaxy_info:
  role_name: pushgateway
  namespace: bodsch

  author: Bodo Schulz
  description: ansible role to setup prometheus-pushgateway
  license: Apache
  min_ansible_version: "2.10"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
    - name: Ubuntu
      versions:
        # 20.04
        - focal
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - prometheus
    - pushgateway
    - collector
    - monitoring
    - metrics
    - system

dependencies: []

...
