---

- name: user and group handling
  when:
    - redis_exporter_system_user != "root"
  block:
    - name: create redis_exporter group
      ansible.builtin.group:
        name: "{{ redis_exporter_system_group }}"
        state: present
        system: true

    - name: create redis_exporter user
      ansible.builtin.user:
        name: "{{ redis_exporter_system_user }}"
        groups: "{{ redis_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ redis_exporter_install_path }}"
    state: directory
    owner: "{{ redis_exporter_system_user }}"
    group: "{{ redis_exporter_system_group }}"
    mode: 0755

- name: detect extracted binary file for redis_exporter on '{{ redis_exporter_delegate_to }}'
  become: false
  delegate_to: "{{ redis_exporter_delegate_to }}"
  run_once: "{{ 'false' if redis_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ redis_exporter_local_tmp_directory }}/{{ redis_exporter_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed redis_exporter binary
  ansible.builtin.stat:
    path: "{{ redis_exporter_install_path }}/{{ redis_exporter_release.binary }}"
  register: stat_redis_exporter_binary

- name: detect activated redis_exporter binary
  ansible.builtin.stat:
    path: /usr/bin/{{ redis_exporter_release.binary }}
  register: stat_redis_exporter_activated

- name: install and activate redis_exporter
  when:
    - (stat_redis_exporter_binary.stat is defined and not stat_redis_exporter_binary.stat.exists | default('false')) or
      not stat_redis_exporter_activated.stat | bodsch.prometheus.linked_version(redis_exporter_install_path, redis_exporter_version)
  block:
    - name: propagate files
      block:
        - name: propagate redis_exporter binary
          ansible.builtin.copy:
            src: "{{ redis_exporter_local_tmp_directory }}/{{ redis_exporter_release.binary }}"
            dest: "{{ redis_exporter_install_path }}/{{ redis_exporter_release.binary }}"
            mode: 0755
            owner: "{{ redis_exporter_system_user }}"
            group: "{{ redis_exporter_system_group }}"
            remote_src: "{{ 'true' if redis_exporter_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ redis_exporter_install_path }}/{{ redis_exporter_release.binary }}"
            mode: 0755
            owner: "{{ redis_exporter_system_user }}"
            group: "{{ redis_exporter_system_group }}"

        - name: ensure redis exporter binary has cap_net_raw capability
          capabilities:
            path: "{{ redis_exporter_install_path }}/{{ redis_exporter_release.binary }}"
            capability: cap_net_raw+ep
            state: present
          when:
            - not ansible_check_mode

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ redis_exporter_install_path }}/{{ redis_exporter_release.binary }}"
            dest: /usr/bin/{{ redis_exporter_release.binary }}
            state: link
            force: true
            follow: false
          notify:
            - restart redis exporter

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ redis_exporter_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create redis_exporter run configuration
      ansible.builtin.template:
        src: "default/redis_exporter.j2"
        dest: "{{ redis_exporter_defaults_directory }}/redis_exporter"
        force: true
        owner: root
        group: "{{ redis_exporter_system_group }}"
        mode: 0640
      notify:
        - restart redis exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/redis_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/redis_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart redis exporter

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/redis_exporter.j2"
        dest: "/etc/conf.d/redis_exporter"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/redis_exporter.j2"
        dest: "/etc/init.d/redis_exporter"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: redis_exporter
    facts:
      version: "{{ redis_exporter_version }}"

...
