---

redis_exporter_version: '1.56.0'

redis_exporter_release: {}

redis_exporter_system_group: redis-exporter
redis_exporter_system_user: redis-exporter
redis_exporter_config_dir: /etc/redis_exporter

redis_exporter_direct_download: false

redis_exporter_service: {}

...
