---

- name: detect binary file for node_exporter
  become: false
  delegate_to: "{{ node_exporter_delegate_to }}"
  run_once: "{{ 'false' if node_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ node_exporter_local_tmp_directory }}/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
  register: stat_file_binary

- name: copy files
  when:
    - stat_file_binary.stat.exists
  block:
    - name: propagate node_exporter binaries
      ansible.builtin.copy:
        src: "{{ node_exporter_local_tmp_directory }}/node_exporter-{{ node_exporter_version }}.linux-amd64//node_exporter"
        dest: "{{ node_exporter_install_path }}/node_exporter"
        mode: 0755
        owner: "{{ node_exporter_system_user }}"
        group: "{{ node_exporter_system_group }}"
        remote_src: "{{ 'true' if node_exporter_direct_download else 'false' }}"

    - name: make files executable
      ansible.builtin.file:
        path: "{{ node_exporter_install_path }}/node_exporter"
        mode: 0755
        owner: "{{ node_exporter_system_user }}"
        group: "{{ node_exporter_system_group }}"

- name: create custom fact file
  bodsch.core.facts:
    name: node_exporter
    facts:
      version: "{{ node_exporter_version }}"

- name: create link to binary
  ansible.builtin.file:
    src: "{{ node_exporter_install_path }}/node_exporter"
    dest: /usr/bin/node_exporter
    state: link
    force: true
    follow: false
  notify:
    - restart node_exporter

- name: create node_exporter data directory
  ansible.builtin.file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: 0755

- name: create systemd service unit
  ansible.builtin.template:
    src: "init/systemd/node_exporter.service.j2"
    dest: "{{ systemd_lib_directory }}/node_exporter.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart node_exporter

...
