---

- name: user and group handling
  when:
    - node_exporter_system_user != "root"
  block:
    - name: create node_exporter group
      ansible.builtin.group:
        name: "{{ node_exporter_system_group }}"
        state: present
        system: true

    - name: create node_exporter user
      ansible.builtin.user:
        name: "{{ node_exporter_system_user }}"
        groups: "{{ node_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ node_exporter_install_path }}"
    state: directory
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: 0755

- name: detect extracted binary file for node_exporter on '{{ node_exporter_delegate_to }}'
  become: false
  delegate_to: "{{ node_exporter_delegate_to }}"
  run_once: "{{ 'false' if node_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ node_exporter_local_tmp_directory }}/{{ node_exporter_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed node_exporter binary
  ansible.builtin.stat:
    path: "{{ node_exporter_install_path }}/{{ node_exporter_release.binary }}"
  register: stat_node_exporter_binary

- name: detect activated node_exporter binary
  ansible.builtin.stat:
    path: "/usr/bin/{{ node_exporter_release.binary }}"
  register: stat_node_exporter_activated

- name: install and activate node_exporter
  when:
    - stat_node_exporter_binary.stat is defined
    - not stat_node_exporter_binary.stat.exists | default('false')
    - stat_node_exporter_activated.stat is defined
    - not stat_node_exporter_activated.stat.exists | default('false')
  block:
    - name: propagate files
      block:
        - name: propagate node_exporter binary
          ansible.builtin.copy:
            src: "{{ node_exporter_local_tmp_directory }}/{{ node_exporter_release.binary }}"
            dest: "{{ node_exporter_install_path }}/{{ node_exporter_release.binary }}"
            mode: 0755
            owner: "{{ node_exporter_system_user }}"
            group: "{{ node_exporter_system_group }}"
            remote_src: "{{ 'true' if node_exporter_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ node_exporter_install_path }}/{{ node_exporter_release.binary }}"
            mode: 0755
            owner: "{{ node_exporter_system_user }}"
            group: "{{ node_exporter_system_group }}"

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ node_exporter_install_path }}/{{ node_exporter_release.binary }}"
            dest: "/usr/bin/{{ node_exporter_release.binary }}"
            state: link
            force: true
            follow: false
          notify:
            - restart node exporter

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ node_exporter_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create node_exporter run configuration
      ansible.builtin.template:
        src: "default/node_exporter.j2"
        dest: "{{ node_exporter_defaults_directory }}/node_exporter"
        force: true
        owner: root
        group: "{{ node_exporter_system_group }}"
        mode: 0640
      notify:
        - restart node exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/node_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/node_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart node exporter

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/node_exporter.j2"
        dest: "/etc/conf.d/node_exporter"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/node_exporter.j2"
        dest: "/etc/init.d/node_exporter"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: node_exporter
    facts:
      version: "{{ node_exporter_version }}"

...
