---

- name: detect external installation
  ansible.builtin.stat:
    path: /usr/local/bin/nginx_exporter
    get_checksum: false
  register: stat_nginx_exporter_path
  ignore_errors: true

- name: old installation
  when:
    - stat_nginx_exporter_path is defined
    - stat_nginx_exporter_path.stat is defined
    - stat_nginx_exporter_path.stat.isdir is defined
    - not stat_nginx_exporter_path.stat.isdir
  block:
    - name: stop old service
      ansible.builtin.service:
        name: nginx_exporter
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      ansible.builtin.file:
        state: absent
        path: /etc/systemd/system/nginx_exporter.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed nginx_exporter
      ansible.builtin.file:
        state: absent
        path: /usr/local/bin/nginx_exporter

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
