---

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - mongodb_exporter_version == "latest"
  block:
    - name: get latest release
      delegate_to: localhost
      become: false
      run_once: true
      bodsch.scm.github_latest:
        project: percona
        repository: mongodb_exporter
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: re-define mongodb_exporter_version
      ansible.builtin.set_fact:
        mongodb_exporter_version: "{{ _latest_release.latest_release }}"

- name: define download information
  ansible.builtin.set_fact:
    mongodb_exporter_release: "{{ mongodb_exporter_defaults_release | combine(mongodb_exporter_release, recursive=True) }}"

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    mongodb_exporter_delegate_to: "{{ ansible_host }}"
    mongodb_exporter_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/mongodb_exporter', true) }}/{{ mongodb_exporter_version }}"
  when:
    - mongodb_exporter_direct_download

- name: create download directory
  become: false
  delegate_to: "{{ mongodb_exporter_delegate_to }}"
  run_once: "{{ 'false' if mongodb_exporter_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ mongodb_exporter_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: detect the downloaded mongodb_exporter archive
  become: false
  delegate_to: "{{ mongodb_exporter_delegate_to }}"
  run_once: "{{ 'false' if mongodb_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ mongodb_exporter_local_tmp_directory }}/{{ mongodb_exporter_release.file }}"
  register: stat_mongodb_exporter_archive

- name: download
  when:
    - stat_mongodb_exporter_archive.stat is defined
    - not stat_mongodb_exporter_archive.stat.exists | default('false')
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: percona
            repository: mongodb_exporter
            checksum_file: mongodb_exporter_{{ mongodb_exporter_version }}_checksums.txt
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "v{{ mongodb_exporter_version }}"
          register: _latest_checksum

        - name: define checksum for {{ system_architecture }} architecture
          ansible.builtin.set_fact:
            __mongodb_exporter_checksum: "sha256:{{ _latest_checksum.checksum }}"
          when:
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download mongodb_exporter binary archive
      become: false
      delegate_to: "{{ mongodb_exporter_delegate_to }}"
      run_once: "{{ 'false' if mongodb_exporter_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ mongodb_exporter_release.download_url }}/download/v{{ mongodb_exporter_version }}/{{ mongodb_exporter_release.file }}"
        dest: "{{ mongodb_exporter_local_tmp_directory }}/{{ mongodb_exporter_release.file }}"
        checksum: "{{ __mongodb_exporter_checksum | default(omit) }}"
        mode: 0640
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ mongodb_exporter_delegate_to }}"
      run_once: "{{ 'false' if mongodb_exporter_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ mongodb_exporter_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect extracted binary
  become: false
  delegate_to: "{{ mongodb_exporter_delegate_to }}"
  run_once: "{{ 'false' if mongodb_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ mongodb_exporter_local_tmp_directory }}/{{ mongodb_exporter_release.binary }}"
  register: stat_mongodb_exporter_binary

- name: extract mongodb_exporter archive
  become: false
  delegate_to: "{{ mongodb_exporter_delegate_to }}"
  run_once: "{{ 'false' if mongodb_exporter_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ mongodb_exporter_local_tmp_directory }}/{{ mongodb_exporter_release.file }}"
    dest: "{{ mongodb_exporter_local_tmp_directory }}/"
    copy: false
    extra_opts:
      - --strip-components=1
  when:
    - stat_mongodb_exporter_binary.stat is defined
    - not stat_mongodb_exporter_binary.stat.exists | default('false')

...
